export const defaultHashtags = [
  "🔍 wanted",
  "🤝 offered",
  "✈️ flight buddy",
  "🏢 NGO",
  "🦴 shelter",
  "🚨 urgent",
  "🏡 foster",
  "🏠 adopt",
  "🦮 dogwalker",
  "🧑 petsitter",
  "👍 volunteer",
  "🟢 found",
  "❌ lost",
  "❤️ rescued",
  "🆘 help",
  "📢 share",
  "🩺 veterinary",
  "🏥 clinic",
  "💵 donate",
  "💰 fundraiser",
  "📅 event",
  "🎓 training",
  "🧠 behavior",
  "✂️ sterilisation"
]

